### ISSUE TITLE
Cannot empty folder because of type(stats,'Stats') is false

### ISSUE THREAD

**Issue by Didji** [devrafalko/empty-folder#1]
Hello!

I'm developing a program which converts CSV files in JSON files and I'm using your module to empty my output folder before creating a new batch of JSON files. 

However, the module kept failing because of this condition : [var isDir = type(stats,'Stats')&&stats.isDirectory();](https://github.com/devrafalko/empty-folder/blob/master/index.js#L46)

I'm not sure what type stats is supposed to be, but it seems it's not 'Stats'. When I removed this part of the condition (leaving only stats.isDirectory()), the module started working fine.

Here's how I'm basically using the module : 
```
const empty = require('empty-folder');
[...]
empty(outputRoot, false, o => {
  if (o.error) console.error(o.error);
  [...]
  createSingleFile(translations, 'en-US', outputRoot);
});
```

I'm using node v6.9.5, npm v5.6.0 and empty-folder v2.0.1.

Thanks for looking into this!

N.B : This same condition exists in the module list-contents, which is used by empty-folder and resulted in the same error ([here](https://github.com/devrafalko/list-contents/blob/master/index.js#L102) and [here](https://github.com/devrafalko/list-contents/blob/master/index.js#L103)).

**Comment by devrafalko** [comment]
The `type()` is the `of-type` package that checks the type of given object/value. In this case the `type(stats,'Stats')` checks if the `stats` object is the instance of Stats constructor (`stats.constructor.name`). Your code works for me with node v6.9.5 and upper. The `type(stats,'Stats')` returns true indeed. You can check in the console what the `fs.stat` returns for you - what the `err` and `stats` is.

```javascript
  function validateRoot(resolve,reject){
    fs.stat(this.rootAbsolute,(err,stats)=>{
      var exists = type(err,null);
      console.log('LOG: ',err,stats);
      var isDir = type(stats,'Stats')&&stats.isDirectory();
      if(exists&&isDir) return resolve();
      if(exists&&!isDir) return reject(new Error(`The given path "${this.rootAbsolute}" is not a directory.`));
      if(!exists) return reject(new Error(`The given path "${this.rootAbsolute}" does not exist or is inaccessible.`));
    });
  }
```

**Comment by Didji** [comment]
Sorry for the delay, here's what I logged:
```
  function validateRoot(resolve,reject){
    fs.stat(this.rootAbsolute,(err,stats)=>{
      var exists = type(err,null);
      console.log('LOG: ',err,stats);
      console.log('type: ',type(stats,'Stats'));
      var isDir = stats.isDirectory();
      if(exists&&isDir) return resolve();
      if(exists&&!isDir) return reject(new Error(`The given path "${this.rootAbsolute}" is not a directory.`));
      if(!exists) return reject(new Error(`The given path "${this.rootAbsolute}" does not exist or is inaccessible.`));
    });
  }
```
And here's the result:
```
LOG:  null { dev: 748170546,
  mode: 16822,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: undefined,
  ino: 1407374884886914,
  size: 0,
  blocks: undefined,
  atime: 2018-05-09T08:56:16.394Z,
  mtime: 2018-05-09T08:56:16.394Z,
  ctime: 2018-05-09T08:56:16.394Z,
  birthtime: 2018-05-04T08:00:24.111Z }
type:  false
```

**Comment by devrafalko** [comment]
The 'LOG' returns the Stats object indeed, but the `type` module returns `false` as if it was not Stats object. Perhaps the problem is with `type` module but I installed your nodeJS version and it works correct for me, so it's quite tough to me to figure out where the problem is. Can you additionally check the following logs? Place them in the same line where the previous ones:

```javascript
console.log('instanceof: ', stats instanceof fs.Stats);
console.log('prototypeof: ', Object.getPrototypeOf(stats).constructor.name);
```

**Comment by Didji** [comment]
Here's the result of the log you asked:

```
instanceof:  true
prototypeof:
```

Additionally, I logged Object.getPrototypeOf(stats):
```
prototypeof:  { _checkModeProperty: [Function],
  isDirectory: [Function],
  isFile: [Function],
  isBlockDevice: [Function],
  isCharacterDevice: [Function],
  isSymbolicLink: [Function],
  isFIFO: [Function],
```
And Object.getPrototypeOf(stats).constructor:
```
prototypeof:  function (
    dev,
    mode,
    nlink,
    uid,
    gid,
    rdev,
    blksize,
    ino,
    size,
    blocks,
    atim_msec,
    mtim_msec,
    ctim_msec,
    birthtim_msec) {
  this.dev = dev;
  this.mode = mode;
  this.nlink = nlink;
  this.uid = uid;
  this.gid = gid;
  this.rdev = rdev;
  this.blksize = blksize;
  this.ino = ino;
  this.size = size;
  this.blocks = blocks;
  this.atime = new Date(atim_msec);
  this.mtime = new Date(mtim_msec);
  this.ctime = new Date(ctim_msec);
  this.birthtime = new Date(birthtim_msec);
}
```

It looks like the constructor doesn't have a name? I'm also using Typescript 2.7.2, if it helps

**Comment by devrafalko** [comment]
For me, the constructor does have a name, also when I compile the .ts file with TypeScript@2.\*.\*. I've finally changed a checking of the `stats` variable's type from `Object.getPrototypeOf(stats).constructor.name` into `instanceof`. [v2.0.2](https://github.com/devrafalko/empty-folder/tree/v2.0.2), [npm](https://www.npmjs.com/package/empty-folder).

**Comment by Didji** [comment]
Just tested it, it works fine with version 2.0.2.

Thanks a lot for your time, I'm closing this issue.
